[package]
name = "bettercp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.17"
libc = "0.2"

[target.'cfg(target_env = "musl")'.dependencies]
tikv-jemallocator = "0.5"
